/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as _protectedRouteImport } from './routes/__protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Oauth2SuccessRouteImport } from './routes/oauth2/success'
import { Route as _protectedCustomerDashboardRouteImport } from './routes/__protected/customer/dashboard'
import { Route as _protectedBarbarSetupProfileRouteImport } from './routes/__protected/barbar/setup-profile'
import { Route as _protectedBarbarDashboardRouteImport } from './routes/__protected/barbar/dashboard'

const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const _protectedRoute = _protectedRouteImport.update({
  id: '/__protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Oauth2SuccessRoute = Oauth2SuccessRouteImport.update({
  id: '/oauth2/success',
  path: '/oauth2/success',
  getParentRoute: () => rootRouteImport,
} as any)
const _protectedCustomerDashboardRoute =
  _protectedCustomerDashboardRouteImport.update({
    id: '/customer/dashboard',
    path: '/customer/dashboard',
    getParentRoute: () => _protectedRoute,
  } as any)
const _protectedBarbarSetupProfileRoute =
  _protectedBarbarSetupProfileRouteImport.update({
    id: '/barbar/setup-profile',
    path: '/barbar/setup-profile',
    getParentRoute: () => _protectedRoute,
  } as any)
const _protectedBarbarDashboardRoute =
  _protectedBarbarDashboardRouteImport.update({
    id: '/barbar/dashboard',
    path: '/barbar/dashboard',
    getParentRoute: () => _protectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/not-found': typeof NotFoundRoute
  '/oauth2/success': typeof Oauth2SuccessRoute
  '/barbar/dashboard': typeof _protectedBarbarDashboardRoute
  '/barbar/setup-profile': typeof _protectedBarbarSetupProfileRoute
  '/customer/dashboard': typeof _protectedCustomerDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/not-found': typeof NotFoundRoute
  '/oauth2/success': typeof Oauth2SuccessRoute
  '/barbar/dashboard': typeof _protectedBarbarDashboardRoute
  '/barbar/setup-profile': typeof _protectedBarbarSetupProfileRoute
  '/customer/dashboard': typeof _protectedCustomerDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/__protected': typeof _protectedRouteWithChildren
  '/not-found': typeof NotFoundRoute
  '/oauth2/success': typeof Oauth2SuccessRoute
  '/__protected/barbar/dashboard': typeof _protectedBarbarDashboardRoute
  '/__protected/barbar/setup-profile': typeof _protectedBarbarSetupProfileRoute
  '/__protected/customer/dashboard': typeof _protectedCustomerDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/not-found'
    | '/oauth2/success'
    | '/barbar/dashboard'
    | '/barbar/setup-profile'
    | '/customer/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/not-found'
    | '/oauth2/success'
    | '/barbar/dashboard'
    | '/barbar/setup-profile'
    | '/customer/dashboard'
  id:
    | '__root__'
    | '/'
    | '/__protected'
    | '/not-found'
    | '/oauth2/success'
    | '/__protected/barbar/dashboard'
    | '/__protected/barbar/setup-profile'
    | '/__protected/customer/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  _protectedRoute: typeof _protectedRouteWithChildren
  NotFoundRoute: typeof NotFoundRoute
  Oauth2SuccessRoute: typeof Oauth2SuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__protected': {
      id: '/__protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _protectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth2/success': {
      id: '/oauth2/success'
      path: '/oauth2/success'
      fullPath: '/oauth2/success'
      preLoaderRoute: typeof Oauth2SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__protected/customer/dashboard': {
      id: '/__protected/customer/dashboard'
      path: '/customer/dashboard'
      fullPath: '/customer/dashboard'
      preLoaderRoute: typeof _protectedCustomerDashboardRouteImport
      parentRoute: typeof _protectedRoute
    }
    '/__protected/barbar/setup-profile': {
      id: '/__protected/barbar/setup-profile'
      path: '/barbar/setup-profile'
      fullPath: '/barbar/setup-profile'
      preLoaderRoute: typeof _protectedBarbarSetupProfileRouteImport
      parentRoute: typeof _protectedRoute
    }
    '/__protected/barbar/dashboard': {
      id: '/__protected/barbar/dashboard'
      path: '/barbar/dashboard'
      fullPath: '/barbar/dashboard'
      preLoaderRoute: typeof _protectedBarbarDashboardRouteImport
      parentRoute: typeof _protectedRoute
    }
  }
}

interface _protectedRouteChildren {
  _protectedBarbarDashboardRoute: typeof _protectedBarbarDashboardRoute
  _protectedBarbarSetupProfileRoute: typeof _protectedBarbarSetupProfileRoute
  _protectedCustomerDashboardRoute: typeof _protectedCustomerDashboardRoute
}

const _protectedRouteChildren: _protectedRouteChildren = {
  _protectedBarbarDashboardRoute: _protectedBarbarDashboardRoute,
  _protectedBarbarSetupProfileRoute: _protectedBarbarSetupProfileRoute,
  _protectedCustomerDashboardRoute: _protectedCustomerDashboardRoute,
}

const _protectedRouteWithChildren = _protectedRoute._addFileChildren(
  _protectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  _protectedRoute: _protectedRouteWithChildren,
  NotFoundRoute: NotFoundRoute,
  Oauth2SuccessRoute: Oauth2SuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
